services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php_native_jwt_tasks
    volumes:
      - .:/var/www/html
    ports:
      - "8585:80"
    working_dir: /var/www
    depends_on:
      - db:
        condition: service_healthy
    environment:
      - JWT_SECRET=supersecretkey_change_this
      - DB_HOST=db
      - DB_NAME=php_native_jwt_tasks
      - DB_USER=root
      - DB_PASS=rootpass
      - DB_PORT=8383
    networks:
      - network_php_native_jwt_tasks

  db:
    image: mysql:8.0
    container_name: db_php_native_jwt_tasks
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
      - ./migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
    ports:
      - 8383:3306
    command: [ 'mysqld', '--default-authentication-plugin=mysql_native_password', '--bind-address=0.0.0.0']
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      start_period: 60s  # â¬† Aumentado a 30s
    networks:
      - network_php_native_jwt_tasks

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: admin_db_php_native_jwt_tasks
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8185:80"
    depends_on:
      - db:
        condition: service_healthy
    networks:
      - network_php_native_jwt_tasks
  
  vscode:
    image: codercom/code-server:latest
    container_name: vscode_php_native_jwt_tasks
    user: "root"
    ports:
      - 3434:8080
    environment:
      - PASSWORD=4nm3r403
      - TZ=America/Bogota
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
      - ./vscode_php/config:/home/coder/.config
      - ./vscode_php/extensions:/home/coder/.local/share/code-server/extensions
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - network_php_native_jwt_tasks
volumes:
  db_data: {}

networks:
  network_php_native_jwt_tasks:
    external: true 
